### PR TITLE
Improved onboarding project to follow a cleaner architecture

### PR DESCRIPTION
**Pull request by juliocatano**
# What's in #
- Added RxBinding to support observables with clicks (this is already included in Excalibur project).
- Refactored tests to considering feeding an observable
- Refactored presenter and view to only have a single observable from view to presenter.

### CODE REVIEW

**Review by capraber — APPROVED** [review]
+1

**Comment by difereto-globant** [comment]
+1

**Comment by jfernandezc** [comment]
+1

**Review by gaston-mira-glb — APPROVED** [review]

**Comment by diegomazzitelli** [comment]
👏

**Pull request merged**
